### ISSUE TITLE
Use import.meta.url

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-modulizer#97]
URLs in CSS were file-relative. After processing with html2js they're main document relative.

There's also the resolveUrl API, which does similar things.

What should we do here?

Failing polymer test to confirm:

unit/custom-style.html
  - style paths in included dom-modules loaded in import

also most of unit/resolveurl.html

**Comment by justinfagnani** [comment]
@kevinpschaaf I'm assigning this to you since I think we can figure this out now that `import.meta.url` is available in Canary. Could this just be handled at runtime in core without modifying template & style source?

**Comment by kevinpschaaf** [comment]
So, just adding a static getter on the class like below to override 2.0's base implementation should provide BC with 2.0's auto identification of the import path based on the `ownerDocument` of the `<template>`:

```js
class XFoo extends Polymer.Element {
  static get importPath() { return import.meta.url; }
}
```

So if `modularizer` just injects that getter it should be good to go.

However, I don't exactly know how to make that more ergonomic for end users writing new 3.0 elements by hand, since as @justin pointed out in an earlier discussion, `import.meta.url` must be evaluated _in the import_ to get the right answer, so this code can't exist in library code like the current implementation of `static get importPath` can.  🤷‍♂️

**Comment by ruphin** [comment]
I have run into the same issue when working with vanilla-ish components, and have come up with the following solution as a patch until `import.meta` lands:

Somewhere in the main document, the user defines a `window.modulesAssetPath` function, which takes a `module` parameter, and returns the path where the assets for that module are found. All modules can use this global function to resolve their own location. It is up to the end user to define the resolution of a module name to a path where the module is installed, which is usually very straightforward, like so:

```javascript
window.modulesAssetPath = function (module) {
    return `/node_modules/${module}`;
  }
```

Modules then use this to resolve relative paths:

```javascript
'./style/layout.css'
```
becomes
```javascript
`${window.modulesAssetPath('moduleName')}/style/layout.css`
```

An example of this can be seen here: https://codepen.io/anon/pen/QOZdjq

If you control the build process it might be possible to automate this completely, otherwise it is up to the consumer to define this function somewhere.

This is the closest solution to `resolveUrl()` that I could find.
